### ISSUE TITLE
Invalid Colour code

### ISSUE THREAD

**Issue by Shayennn** [DormLife-SoftEng/Frontend#2]
dc3545 -> sign up page
rgb(245, 94, 97) -> signin page

![image](https://user-images.githubusercontent.com/8080856/95069955-9df80080-0731-11eb-9ff4-7614e3abea8e.png)
![image](https://user-images.githubusercontent.com/8080856/95070137-dbf52480-0731-11eb-9e2b-7723ea20d82c.png)

**Comment by Peachzxzx** [comment]
Fixed
